### PR TITLE
enh: Add script to automatize save and push WIP DO NOT MERGE

### LINKED ISSUE #177: Consider alternatives to dropbox for synchronization
In addition to Dropbox (why not, it is easy), I think we would want to have the data synchronized in additional ways:

- [ ] Datalad (the EDF files and the acq files are added and pushed to the remote right after every session)
- [ ] [lsyncd](https://github.com/lsyncd/lsyncd) This is not exclusive with datalad, we could use the lsyncd to trigger the datalad add and push operations.

### PR DESCRIPTION
**Pull request by esavary**
This script activates an Anaconda environment, monitors the datalad folder in which we save the Psychopy output for file changes using inotifywait, and performs datalad operations (save and push) in response to changes. It ensures data synchronization while the Anaconda environment is active. closes #177

### CODE REVIEW

**Comment by esavary** [comment]
The idea would be to daemonize this script, but the main challenge right now is that it requires the VPN to be active.
I'm open to ideas on how we can work around the VPN requirement. (Maybe @oesteban @celprov @acionca  )
In addition, we should also decide on other sibling repositories. The one in the script was only used for testing purposes.
Your thoughts and suggestions are much appreciated!

**Comment by oesteban** [comment]
Please read the data management section after we merged #188 and #118 because it affects the datalad save/push.

**Comment by oesteban** [comment]
I think yesterday's happenstance is a strong argument in favor of converting physio and ET into BIDS right away.

**Comment by oesteban** [comment]
It seems we will finally not implement datalad this early. Let's close this one and perhaps recover the idea of a daemon watching changes for the future (I'm imagining, e.g., to trigger an rsync).

**Pull request closed without merging**
